Add error message to workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -31,14 +31,15 @@ jobs:
           git fetch --tags --force
           CURRENT=$(jq -r '.version' manifest.json)
           LATEST=$(git tag | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+' | tail -1)
-          echo Latest version is $LATEST, current version is $CURRENT
-          [[ $CURRENT < $LATEST ]] && echo all bad
-
-
-  # zip_build:
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - run: echo 'hello there'
+          if [[ $CURRENT < $LATEST ]]; then
+            echo "ERROR: current mainfest version $CURRENT is lower than latest version $LATEST"
+            exit 1
+          fi
+          echo "Version $CURRENT is valid, continuing to build"
+  zip_build:
+    runs-on: ubuntu-latest
+    steps:
+      - run: echo 'hello there'
 
   # deploy-chrome:
   #   runs-on: ubuntu-latest
